name: Deploy Backend Lambda

on:
  push:
    paths:
      - 'modules/**'
      - 'terraform/environments/dev/**'
      - '.github/workflows/backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan

        - name: Terraform Apply
        working-directory: terraform/environments/dev
        run: terraform apply -auto-approve \
             -var "aws_access_key=$AWS_ACCESS_KEY_ID" \
             -var "aws_secret_key=$AWS_SECRET_ACCESS_KEY"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      
